# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25a3cbb020decf9f578e64cdc063d60e9aa5490b7f3db1cf696a2fb05927fb28a25790cc3d4a0560b2e54dc518c019df8c007b8b2742d5c4b17cdf2977f9a17d

test:
  secret_key_base: d1317d15523b004f4f839155a0aa96ef92caab223417810e0d83b260eb39bcb5152a0dad863832cea014e276a1b5d80a56d557a9e26b10298c4327f5139226e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
